name: Build Artalk-FreeBSD

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Artalk-FreeBSD
    steps:
    - uses: actions/checkout@v4
    - name: Build Artalk-FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        release: 13.2
        prepare: |
          pkg install -y node wget curl git go121 gcc bash gawk gsed
          ln -s /usr/local/bin/go121 /usr/local/bin/go
        run: |
          git clone https://github.com/ArtalkJS/Artalk.git Artalk
          cd Artalk
          bash ../build.sh
          
    - name: Upload artifact
      uses: actions/upload-artifact@main
      with:
        name: artalk-freebsd
        path: |
            Artalk/bin/artalk-freebsd.moe

    - name: Generate release tag
      id: tag
      run: echo "release_tag=$(wget -qO- https://api.github.com/repos/ArtalkJS/Artalk/tags | gawk -F '["v]' '/name/{print "v"$5;exit}')" >> $GITHUB_OUTPUT

    - name: Create release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
              Artalk/bin/artalk-freebsd.moe
              
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: 'SinzMise/artalk-deploy'
        retain_days: 1
        keep_minimum_runs: 8
