name: update-artalk

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  GITHUB_NAME: ${{ secrets.GH_NAME }} # 你的github昵称
  GITHUB_EMAIL: ${{ secrets.GH_EMAIL }} # 你的github邮箱
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # github token

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Clone Artalk #Artalk更新
      run: |
        git clone https://github.com/ArtalkJS/Artalk.git
        mv ./Artalk/go.mod ./go.mod

    -  name: Get go.mod details
       uses: Eun/go-mod-details@v1
       id: go-mod-details

    - name: Update Artalk #Artalk更新
      run: |
        cd Artalk
        make all
        mv ./bin/artalk ../artalk.moe
        cd ..

    - name: Push Artalk # 最新版Artalk上传
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Update Artalk"
        files: artalk.moe
        rebase: 'true'
        name: ${{ env.GITHUB_NAME }}
        email: ${{ env.GITHUB_EMAIL }}
